name: Discord on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Post to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          echo '${{ toJson(github.event.commits) }}' > commits.json

          # Build a single message with all commits
          MESSAGE="📢 **${{ github.event.pusher.name }}** pushed to \`main\`:"$'\n'

          jq -r '.[] | "\(.message | split("\n")[0]) by **\(.author.name)**", .url' commits.json >> commit_lines.txt

          while IFS= read -r line; do
            MESSAGE+="$line"$'\n'
          done < commit_lines.txt

          # Send to Discord
          jq -n --arg content "$MESSAGE" '{content: $content}' > payload.json

          curl -X POST -H "Content-Type: application/json" \
            -d @payload.json \
            "$DISCORD_WEBHOOK"
