name: Discord on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Post to Discord
        run: |
          AUTHOR="${{ github.event.head_commit.author.name }}"
          URL="${{ github.event.head_commit.url }}"

          # Generate JSON payload
          jq -n \
            --arg content "📢 **$AUTHOR** pushed to \`main\`:" \
            --arg url "$URL" \
            '{content: ($content + "\n" + $url)}' > payload.json

          # Send to Discord
          curl -X POST -H "Content-Type: application/json" \
            -d @payload.json \
            ${{ secrets.DISCORD_WEBHOOK }}
