name: Discord on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Post to Discord
        run: |
          AUTHOR="${{ github.event.head_commit.author.name }}"
          MESSAGE="${{ github.event.head_commit.message }}"
          URL="${{ github.event.head_commit.url }}"

          # Escape special characters for JSON
          ESCAPED_MESSAGE=$(jq -Rn --arg msg "$MESSAGE" '$msg')

          curl -X POST -H "Content-Type: application/json" \
            -d "{
              \"content\": \"📢 **$AUTHOR** pushed to \`main\`:\n> $ESCAPED_MESSAGE\n🔗 $URL\"
            }" \
            ${{ secrets.DISCORD_WEBHOOK }}
